# Generated by Django 5.0 on 2024-01-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
    ]
