# Generated by Django 5.0.2 on 2024-03-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_remove_product_brand_remove_product_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
