# Generated by Django 5.0.2 on 2024-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_remove_product_credit_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Скидка'),
        ),
    ]
