# Generated by Django 5.0.1 on 2024-01-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_remove_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.brand', verbose_name='Бренд товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(default=1, max_length=150, verbose_name='Код цвета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Навзание цыета'),
            preserve_default=False,
        ),
    ]
