# Generated by Django 5.0.1 on 2024-01-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_product_brand_product_color_code_product_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
    ]
