# Generated by Django 4.2.11 on 2024-03-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_product_discount'),
        ('digital', '0010_alter_customer_user'),
    ]

    operations = [
    ]
