# Generated by Django 4.2.11 on 2024-03-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0011_merge_0004_product_discount_0010_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.brand', verbose_name='Бренд товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='credit',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Рассрочка'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ширина'),
        ),
    ]
