# Generated by Django 4.2.11 on 2024-03-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0012_product_brand_product_credit_product_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
